ci:
    autoupdate_schedule: monthly
    autofix_prs: true
    skip: [mypy, pylint, dm-generate-all, dependencies, verdi-autodocs]

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 'v4.1.0'
    hooks:
    -   id: double-quote-string-fixer
    -   id: end-of-file-fixer
        exclude: &exclude_pre_commit_hooks >
            (?x)^(
                tests/.*(?<!\.py)$|
                docs/source/.+\.aiida/repo/.+|
            )$
    -   id: fix-encoding-pragma
    -   id: mixed-line-ending
    -   id: trailing-whitespace
        exclude: *exclude_pre_commit_hooks
    -   id: check-yaml

-   repo: https://github.com/pycqa/isort
    rev: '5.10.1'
    hooks:
    -   id: isort

-   repo: https://github.com/ikamensh/flynt/
    rev: '0.76'
    hooks:
    -   id: flynt

-   repo: https://github.com/pre-commit/mirrors-yapf
    rev: 'v0.32.0'
    hooks:
    -   id: yapf
        name: yapf
        types: [python]
        exclude: &exclude_files >
            (?x)^(
                docs/.*|
            )$
        args: ['-i']
        additional_dependencies: ['toml']

-   repo: https://github.com/PyCQA/pylint
    rev: 'v2.15.3'
    hooks:
    -   id: pylint
        additional_dependencies:
        -   aiida-core[atomic_tools]>=1.2.1
        -   pytest
        -   numpy
        exclude: >
            (?x)^(
                docs/.*|
                examples/.*|
            )$
